const CATALOG = [
    {
        'id': 'el1',
        'name': 'FENDER SQUIER BULLET STRAT HT HSS BLK',
        // 'img': 'https://i.ibb.co/QJfqs4K/1.jpg',
        'img': 'img/1.jpeg',
        'price': 13600,
        'currency': 'USD',
    },
    {
        'id': 'el2',
        'name': 'FENDER SQUIER AFFINITY',
        // 'img': 'https://i.ibb.co/pKrG5ZJ/2.jpg',
        'img': 'img/1.jpeg',
        'price': 23900,
        'currency': 'USD',
    },
    {
        'id': 'el3',
        'name': 'IBANEZ GIO GRG121DX-BKF BLACK FLAT',
        // 'img': 'https://i.ibb.co/NnvcYhR/3.jpg',
        'img': 'img/1.jpeg',
        'price': 21600,
        'currency': 'USD',
    },
    {
        'id': 'el4',
        'name': 'EPIPHONE LES PAUL STUDIO LT EBONY',
        // 'img': 'https://i.ibb.co/4Tg91WL/4.jpg',
        'img': 'img/1.jpeg',
        'price': 19900,
        'currency': 'USD',
    },
    {
        'id': 'el5',
        'name': 'FENDER SQUIER BULLET TREM HSS AWT',
        // 'img': 'https://i.ibb.co/MC7sy1F/5.jpg',
        'img': 'img/1.jpeg',
        'price': 14500,
        'currency': 'USD',
    },
    {
        'id': 'el6',
        'name': 'FENDER SQUIER BULLET MUSTANG HH BLK',
        // 'img': 'https://i.ibb.co/qNBWPb0/6.jpg',
        'img': 'img/1.jpeg',
        'price': 14600,
        'currency': 'USD',
    },
    {
        'id': 'el7',
        'name': 'FENDER SQUIER BULLET STRAT HT AWT',
        // 'img': 'https://i.ibb.co/WH1h2wV/7.jpg',
        'img': 'img/1.jpeg',
        'price': 13600,
        'currency': 'USD',
    },
    {
        'id': 'el8',
        'name': 'JACKSON JS22-7 DINKY SATIN BLACK',
        // 'img': 'https://i.ibb.co/2cBg9g9/8.jpg',
        'img': 'img/1.jpeg',
        'price': 28700,
        'currency': 'USD',
    },
    {
        'id': 'el9',
        'name': 'JACKSON JS11 DINKY OLYMPIC WHITE',
        // 'img': 'https://i.ibb.co/wKxFRM8/9.jpg',
        'img': 'img/1.jpeg',
        'price': 18100,
        'currency': 'USD',
    },
    {
        'id': 'el10',
        'name': 'YAMAHA PACIFICA 012 WH',
        // 'img': 'https://i.ibb.co/30qJcZX/10.jpg',
        'img': 'img/1.jpeg',
        'price': 15990,
        'currency': 'USD',
    }
]